### ISSUE TITLE
`Node :a is not in the graph` error

### ISSUE THREAD

**Issue by kozaxinan** [autonomousapps/dependency-analysis-android-gradle-plugin#386]
**Build scan link**

**Plugin version**

0.72.0

**Gradle version**
 7.0

**Android Gradle Plugin (AGP) version**
 4.1.3

**Describe the bug**

Running buildHealth fails error.

```
Execution failed for task ':template:measureProject'.
> Node :schufa is not in the graph
```

template module doesnt depend on schufa. templete and schufa modules are only used in app module.

**To Reproduce**
1. ... I have no idea how to reproduce.

**Expected behavior**

0.72 should work as 0.71.

```
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':template:measureProject'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:187)
        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:268)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:185)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:173)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:109)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        ...
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
Caused by: java.lang.IllegalArgumentException: Node :schufa is not in the graph
        at com.autonomousapps.graph.DependencyGraphKt.missingNode(DependencyGraph.kt:203)
        at com.autonomousapps.graph.DependencyGraph.adj(DependencyGraph.kt:98)
        at com.autonomousapps.graph.DependencyGraph.adj(DependencyGraph.kt:89)
        at com.autonomousapps.graph.DepthFirstSearch.dfs(DepthFirstSearch.kt:19)
        at com.autonomousapps.graph.DepthFirstSearch.<init>(DepthFirstSearch.kt:14)
        at com.autonomousapps.graph.DepthFirstSearch.<init>(DepthFirstSearch.kt:9)
        at com.autonomousapps.graph.DependencyGraph.subgraph(DependencyGraph.kt:135)
        at com.autonomousapps.graph.DependencyGraph.removeEdges(DependencyGraph.kt:170)
        at com.autonomousapps.tasks.ProjectMetricsTask$expectedResultGraph$2.invoke(ProjectMetricsTask.kt:79)
        at com.autonomousapps.tasks.ProjectMetricsTask$expectedResultGraph$2.invoke(ProjectMetricsTask.kt:24)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at com.autonomousapps.tasks.ProjectMetricsTask.getExpectedResultGraph(ProjectMetricsTask.kt)
        at com.autonomousapps.tasks.ProjectMetricsTask.action(ProjectMetricsTask.kt:60)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:104)
        ...
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)

```

**Comment by plastiv** [comment]
I'm seeng similar error. Since I haven't merged suggestions yet. I can tell one more piece of information which is likely a coincidence but who knows:

* Running 0.72 on main + applied 0.71 suggestions results in "Node is not in the graph" error. 
* While running 0.72 on main without suggestions doesn't errored and prints suggestions as expected.

I don't know if there are docs, but what "Node is not in the graph" error should mean, is this internal or end user facing suggestion?

**Comment by autonomousapps** [comment]
@kozaxinan do you happen to have a build scan link?

@plastiv that error is intended to validate an invariant. If you're seeing it, something is quite wrong in one of the graph-related algorithms and/or data structures. The fact that you can only reproduce it when running 0.72 and applying suggestions from 0.71 suggests it might be an up-to-date-ness issue. Could you try the following?

1. Run 0.71 and apply suggestions
2. Run 0.72 like this: `./gradlew clean buildHealth --no-build-cache`

If doing this does not reproduce the issue, it very strongly suggests it's an up-to-dateness issue, meaning one or more of the inputs to one or more tasks either have the wrong input annotation or there's an implicit input not properly accounted for.

A build scan for the failing (and maybe successful) builds would be helpful.

**Comment by kozaxinan** [comment]
Here is scan with 0.72 with rerun-tasks, it was successful
https://scans.gradle.com/s/khttpsaixw3e4

failed run scan after 0.71 update
https://scans.gradle.com/s/i57vzxb6ylfs6

**Comment by autonomousapps** [comment]
That is strong evidence in favor of my theory that there's an issue with task input correctness. These build scans will be very helpful, thank you.

**Comment by autonomousapps** [comment]
So I found a really fun bug, that has been around for a long time, but is only visible because of the recent change that had strict input validation. I think/hope it resolves this issue. Thank you again for reporting and providing the build scans. Would have been very hard to diagnose without that.

**Comment by autonomousapps** [comment]
Re-opening until I can get someone to confirm that the change fixes this issue. I'll push a release probably today.

**Comment by technoir42** [comment]
I can confirm that this bug is fixed in 0.72.1-SNAPSHOT.

**Comment by autonomousapps** [comment]
@kozaxinan I have just released 0.73.0 (identical to the 0.72.1-SNAPSHOT), which I believe resolves this issue. If not, please feel free to re-open.

**Comment by kozaxinan** [comment]
I tested 0.73, error doesnt occur anymore. Thank you for quick fix and release. 💯

**Comment by Poojith** [comment]
I'm on `v0.75.0` and I'm seeing this error on one of our projects. 

```
> Task :publisher-root:measureProject FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':publisher-root:measureProject'.
> Node :publisher-root is not in the graph
```

I tried running the build with `./gradlew clean buildHealth --no-build-cache`, but the issue persists. Here's what I'm seeing from the stacktrace:

```
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':publisher-root:measureProject'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:208)
        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:263)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:206)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:187)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:114)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
...
   at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
Caused by: java.lang.IllegalArgumentException: Node :publisher-root is not in the graph
        at com.autonomousapps.graph.DependencyGraphKt.missingNode(DependencyGraph.kt:203)
        at com.autonomousapps.graph.DependencyGraph.adj(DependencyGraph.kt:98)
        at com.autonomousapps.graph.DependencyGraph.adj(DependencyGraph.kt:89)
        at com.autonomousapps.graph.DepthFirstSearch.dfs(DepthFirstSearch.kt:19)
        at com.autonomousapps.graph.DepthFirstSearch.<init>(DepthFirstSearch.kt:14)
...
     at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
```

Unfortunately, I'm not able to share the related build scan because this is executed on an internal host, which requires access through a VPN.

**Comment by autonomousapps** [comment]
@Poojith could you try 0.77?

**Comment by niktekusho** [comment]
Hi, we're having the same problem with the 0.80 version on a newly created project (no sources yet).

Link to a build scan: https://scans.gradle.com/s/u7kvzlq2bkwkg

One thing to note is that the project in which the `measureProject` task fails differ randomly between hosts. 

The plugin is applied and configured from the root project using the new version catalog feature:

**rootproject.gradle**
```
plugins {
	alias(libs.plugins.dependencyAnalysisPlugin)
}

// ...

dependencyAnalysis {
	issues {
		all {
			onAny {
				severity('fail') // default is 'warn'
			}
		}
	}
}

```

Other plugins are applied using the conventions plugins created in buildSrc.
If you need anything apart of source code, ask away and we might be able to reply.
Thank you.

**Comment by autonomousapps** [comment]
Could you try the latest version? 

On March 15, 2022, GitHub ***@***.***> wrote:
> Hi, we're having the same problem with the 0.80 version on a newly
> created project (no sources yet).
>
> Link to a build scan: <https://scans.gradle.com/s/u7kvzlq2bkwkg>
>
> One thing to note is that the project in which the measureProject task
> fails differ randomly between hosts.
>
> The plugin is applied and configured from the root project using the
> new version catalog feature:
>
> rootproject.gradle
>
> plugins { alias(libs.plugins.dependencyAnalysisPlugin) } // ...
> dependencyAnalysis { issues { all { onAny { severity('fail') //
> default is 'warn' } } } }
> Other plugins are applied using the conventions plugins created in
> buildSrc.
>  If you need anything apart of source code, ask away and we might be
> able to reply.
>  Thank you.
>

—
Reply to this email directly, view it on GitHub
<https://github.com/autonomousapps/dependency-analysis-android-gradle-
plugin/issues/386#issuecomment-1067859779>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/ABJG5PL3P2FH6RPHGMCHXRLVABWCBANCNFSM43VMC2OA>.
Triage notifications on the go with GitHub Mobile for iOS
<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-
email&mt=8&pt=524675> or Android
<https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-
email%26utm_medium%3Demail%26utm_source%3Dgithub>.
You are receiving this because you modified the open/close state.Message
ID: <autonomousapps/dependency-analysis-android-gradle-
***@***.***>

**Comment by niktekusho** [comment]
> Could you try the latest version? 

Is it version [v1.0.0-rc03](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/releases/tag/v1.0.0-rc03)?

**Comment by autonomousapps** [comment]
Yes. 

On March 17, 2022, GitHub ***@***.***> wrote:
> > Could you try the latest version? 
> >
>
> Is it version v1.0.0-rc03
> <https://github.com/autonomousapps/dependency-analysis-android-gradle-
> plugin/releases/tag/v1.0.0-rc03>?
>

—
Reply to this email directly, view it on GitHub
<https://github.com/autonomousapps/dependency-analysis-android-gradle-
plugin/issues/386#issuecomment-1070932361>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/ABJG5PKJMCZYIECX3PT6353VAMYHPANCNFSM43VMC2OA>.
Triage notifications on the go with GitHub Mobile for iOS
<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-
email&mt=8&pt=524675> or Android
<https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-
email%26utm_medium%3Demail%26utm_source%3Dgithub>.
You are receiving this because you modified the open/close state.Message
ID: <autonomousapps/dependency-analysis-android-gradle-
***@***.***>

**Comment by niktekusho** [comment]
> Yes. 

Happy to report that v1.0.0-rc03 fixes our issue. Thank you!
Any ETA on the 1.0.0 release?

**Comment by autonomousapps** [comment]
"When it's ready." 

On March 21, 2022, GitHub ***@***.***> wrote:
> > Yes. 
> >
>
> Happy to report that v1.0.0-rc03 fixes our issue. Thank you!
>  Any ETA on the 1.0.0 release?
>

—
Reply to this email directly, view it on GitHub
<https://github.com/autonomousapps/dependency-analysis-android-gradle-
plugin/issues/386#issuecomment-1073681852>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/ABJG5PMWYDI3DPVDAHQFRKDVBA7GHANCNFSM43VMC2OA>.
Triage notifications on the go with GitHub Mobile for iOS
<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-
email&mt=8&pt=524675> or Android
<https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-
email%26utm_medium%3Demail%26utm_source%3Dgithub>.
You are receiving this because you modified the open/close state.Message
ID: <autonomousapps/dependency-analysis-android-gradle-
***@***.***>
